# Generated by Django 5.1.5 on 2025-11-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lvl', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
            ],
        ),
    ]
