# Generated by Django 5.1.5 on 2025-11-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='maly_kelimek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='panak',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='velky_kelimek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='lvl',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='xp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
