# Generated by Django 5.1.5 on 2025-11-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_maly_kelimek_player_panak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='xp_need',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='xp',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
