# Generated by Django 5.1.5 on 2025-11-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_xp_need_alter_player_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='side_quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('xp_reward', models.IntegerField(blank=True, default=0)),
                ('rarity', models.CharField(blank=True, choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_quests', to='game.player')),
            ],
        ),
    ]
