# Generated by Django 5.1.5 on 2025-11-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_side_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_quest',
            name='advisor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='side_quest',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
