# Generated by Django 5.1.5 on 2025-11-25 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_side_quest_databese'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='armor',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='player',
            name='dmg',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='energie',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='player',
            name='hp',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='povolani',
            field=models.CharField(blank=True, choices=[('mag', 'Kouzelník'), ('valecnik', 'Válečník'), ('hunter', 'Hunter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='lvl',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='xp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
