# Generated by Django 5.1.5 on 2025-11-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_player_armor_player_dmg_player_energie_player_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='povolani',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
