# Generated by Django 5.1.5 on 2025-11-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_player_povolani'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='armor_koef',
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='dmg_koef',
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='hp_koef',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
