# Generated by Django 5.1.5 on 2025-11-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_player_armor_koef_player_dmg_koef_player_hp_koef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='armor',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='dmg',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='hp',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
