# Generated by Django 5.1.5 on 2025-11-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_player_armor_alter_player_dmg_alter_player_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='armor_now',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='dmg_now',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='hp_now',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
