# Generated by Django 5.1.5 on 2025-11-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_player_armor_now_player_dmg_now_player_hp_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='xp_need',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
