# Generated by Django 5.1.5 on 2025-11-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_player_xp_need'),
    ]

    operations = [
        migrations.CreateModel(
            name='pocet_hracu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet', models.IntegerField(default=1)),
            ],
        ),
    ]
