# Generated by Django 5.1.5 on 2025-11-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_pocet_hracu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pocet_hracu',
            old_name='pocet',
            new_name='pocet_hracu_full',
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='pocet_hracu_now',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='pocet_hracu_off',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='povolani',
            field=models.CharField(blank=True, default='nic', max_length=50),
        ),
    ]
