# Generated by Django 5.1.5 on 2025-11-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_pocet_pocet_hracu_pocet_hracu_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
