# Generated by Django 5.1.5 on 2025-11-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_player_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hp_actual_fight',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
