# Generated by Django 5.1.5 on 2025-11-28 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_player_hp_actual_fight'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dmg_delt', models.IntegerField(blank=True, default=0)),
                ('best_dmg_delt', models.IntegerField(blank=True, default=0)),
                ('total_dmg_taken', models.IntegerField(blank=True, default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='game.player')),
            ],
        ),
    ]
