# Generated by Django 5.1.5 on 2025-11-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
