# Generated by Django 5.1.5 on 2025-12-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_player_hp',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_players_armor',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_players_dmg',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
