# Generated by Django 5.1.5 on 2025-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_pocet_hracu_all_player_hp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jmena_hracu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
