# Generated by Django 5.1.5 on 2025-12-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_jmena_hracu'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_quest_databese',
            name='quest_type',
            field=models.CharField(blank=True, choices=[('alko', 'Alko'), ('nealko', 'Nealko'), ('coop', 'Coop')], max_length=100),
        ),
    ]
