# Generated by Django 5.1.5 on 2025-12-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_side_quest_databese_quest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_quest',
            name='player_coop',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='side_quest',
            name='quest_type',
            field=models.CharField(blank=True, choices=[('alko', 'Alko'), ('nealko', 'Nealko'), ('coop', 'Coop')], max_length=100),
        ),
    ]
