# Generated by Django 5.1.5 on 2025-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_side_quest_player_coop_side_quest_quest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='death_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
