# Generated by Django 5.1.5 on 2025-12-05 05:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_achievements_death_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_energy_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='energie',
            field=models.IntegerField(blank=True, default=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
