# Generated by Django 5.1.5 on 2025-12-05 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_player_last_energy_update_alter_player_energie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_energy_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
