# Generated by Django 5.1.5 on 2025-12-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_player_last_energy_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score_best_dmg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='score_death_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='score_dmg_delt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='score_dmg_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_best_dmg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_death_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_dmg_delt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_dmg_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
