# Generated by Django 5.1.5 on 2025-12-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_player_score_best_dmg_player_score_death_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_score_best_dmg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_score_death_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_score_dmg_delt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pocet_hracu',
            name='all_score_dmg_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
