# Generated by Django 5.1.5 on 2025-12-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_pocet_hracu_all_score_pocet_hracu_all_score_best_dmg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
