# Generated by Django 5.1.5 on 2025-12-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_player_skill_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
