# Generated by Django 5.1.5 on 2025-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_player_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role_img_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
