# Generated by Django 5.1.5 on 2025-12-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_player_role_img_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_quest',
            name='coop_player_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='side_quest',
            name='player_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
