# Generated by Django 5.1.5 on 2025-12-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_side_quest_coop_player_name_side_quest_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmena_hracu',
            name='player_profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
