# Generated by Django 5.1.5 on 2025-12-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_player_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmena_hracu',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
