# Generated by Django 5.1.5 on 2025-12-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_jmena_hracu_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='side_quest_generated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(blank=True, max_length=100)),
                ('quest_type', models.CharField(blank=True, choices=[('alko', 'Alko'), ('nealko', 'Nealko'), ('coop', 'Coop')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('xp_reward', models.IntegerField(blank=True, default=0)),
                ('rarity', models.CharField(blank=True, choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='side_quest_databese',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='side_quest_databese',
            name='xp_reward',
        ),
    ]
