# Generated by Django 5.1.5 on 2025-12-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_side_quest_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_quest_generated',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_quests_generated', to='game.player'),
        ),
    ]
