# Generated by Django 5.1.5 on 2025-12-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_side_quest_generated_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='side_quest',
            name='advisor',
        ),
    ]
