# Generated by Django 5.1.5 on 2025-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_remove_side_quest_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='quest_refresh',
            field=models.IntegerField(default=1),
        ),
    ]
