# Generated by Django 5.1.5 on 2025-12-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_test_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='attack_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
