# Generated by Django 5.1.5 on 2025-12-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_achievements_attack_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='attack_get',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
