# Generated by Django 5.1.5 on 2025-12-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_achievements_attack_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='maly_kelimek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='achievements',
            name='panaky',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='achievements',
            name='velky_kelimek',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
