# Generated by Django 5.1.5 on 2025-12-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_achievements_maly_kelimek_achievements_panaky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='critic_chance',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dodge_chance',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
