# Generated by Django 5.1.5 on 2025-12-27 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_player_critic_chance_player_dodge_chance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='critic_chance',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='dodge_chance',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
