# Generated by Django 5.1.5 on 2025-12-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0044_alter_player_critic_chance_alter_player_dodge_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Quest_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
