# Generated by Django 5.1.5 on 2025-12-29 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_player_quest_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Quest_counter',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
