# Generated by Django 5.1.5 on 2025-12-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_alter_player_quest_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Quest_counter',
            new_name='quest_counter',
        ),
    ]
