# Generated by Django 5.1.5 on 2025-12-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_rename_quest_counter_player_quest_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_quest',
            name='dificulty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='side_quest_databese',
            name='dificulty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='side_quest_generated',
            name='dificulty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
