# Generated by Django 5.1.5 on 2025-11-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patro', models.IntegerField(default=1)),
                ('lvl', models.IntegerField(default=1)),
                ('dmg', models.IntegerField(default=1)),
                ('armor', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=10)),
                ('reward_xp', models.IntegerField(default=10)),
            ],
        ),
    ]
