# Generated by Django 5.1.5 on 2025-11-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='defeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boss',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
