# Generated by Django 5.1.5 on 2025-11-26 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0002_boss_defeated_boss_description'),
        ('game', '0016_player_hp_actual_fight'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_time', models.DateTimeField(auto_now_add=True)),
                ('player_count', models.IntegerField(verbose_name='Počet aktivních hráčů')),
                ('outcome', models.CharField(choices=[('players', 'Hráči zvítězili'), ('boss', 'Boss zvítězil'), ('draw', 'Remíza (nepravděpodobné)')], default='draw', max_length=10)),
                ('total_damage_dealt_by_players', models.IntegerField(default=0)),
                ('total_damage_received_by_players', models.IntegerField(default=0)),
                ('final_boss_hp', models.IntegerField(verbose_name='Konečné HP Bosse')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_logs', to='fightapp.boss')),
            ],
        ),
        migrations.CreateModel(
            name='TurnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('attacker_is_boss', models.BooleanField(default=False)),
                ('damage_dealt', models.IntegerField(verbose_name='Udělené poškození')),
                ('attacker_damage_roll', models.IntegerField(verbose_name='Základní hod útočníka před brněním')),
                ('target_armor_roll', models.IntegerField(verbose_name='Hod brnění cíle')),
                ('boss_hp_after', models.IntegerField(verbose_name='HP Bosse po tahu')),
                ('target_player_hp_after', models.IntegerField(blank=True, null=True, verbose_name='HP Hráče po tahu')),
                ('attacker_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_turns', to='game.player')),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_logs', to='fightapp.fightlog')),
                ('target_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_turns', to='game.player')),
            ],
        ),
    ]
