# Generated by Django 5.1.5 on 2025-11-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0003_fightlog_turnlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightlog',
            name='final_boss_hp',
            field=models.IntegerField(default=0, verbose_name='Konečné HP Bosse'),
        ),
    ]
