# Generated by Django 5.1.5 on 2025-12-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0004_alter_fightlog_final_boss_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='boss_names_descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patro', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
