# Generated by Django 5.1.5 on 2025-12-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0005_boss_names_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss_names_descriptions',
            name='boss_img',
            field=models.ImageField(blank=True, null=True, upload_to='boss_images/'),
        ),
    ]
