# Generated by Django 5.1.5 on 2025-12-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0006_boss_names_descriptions_boss_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnlog',
            name='boss_max_hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximální HP Bosse'),
        ),
        migrations.AddField(
            model_name='turnlog',
            name='target_player_max_hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximální HP Hráče'),
        ),
    ]
