# Generated by Django 5.1.5 on 2025-12-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0007_turnlog_boss_max_hp_turnlog_target_player_max_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='boss_img',
            field=models.ImageField(blank=True, null=True, upload_to='boss_images/'),
        ),
    ]
