# Generated by Django 5.1.5 on 2025-12-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0008_boss_boss_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='critic_chance',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='boss',
            name='dodge_chance',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
