# Generated by Django 5.1.5 on 2025-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0009_boss_critic_chance_boss_dodge_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnlog',
            name='bojovy_postoj_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Stav bojového postoje'),
        ),
        migrations.AddField(
            model_name='turnlog',
            name='critic_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Stav kritického zásahu'),
        ),
    ]
