# Generated by Django 5.1.5 on 2025-12-27 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0010_turnlog_bojovy_postoj_status_turnlog_critic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='critic_chance',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='boss',
            name='dmg',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='boss',
            name='dodge_chance',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
