# Generated by Django 5.1.5 on 2025-12-29 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0011_alter_boss_critic_chance_alter_boss_dmg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fight_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('total_dmg_delt', models.IntegerField(blank=True, default=0)),
                ('best_dmg_delt', models.IntegerField(blank=True, default=0)),
                ('total_dmg_taken', models.IntegerField(blank=True, default=0)),
                ('death_counter', models.IntegerField(blank=True, default=0)),
                ('attack_counter', models.IntegerField(blank=True, default=0)),
                ('attack_get', models.IntegerField(blank=True, default=0)),
                ('crit_number', models.IntegerField(blank=True, default=0)),
                ('dodge_number', models.IntegerField(blank=True, default=0)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_histories', to='fightapp.fightlog')),
            ],
        ),
    ]
