# Generated by Django 5.1.5 on 2025-12-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0012_fight_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight_history',
            name='player_name',
        ),
        migrations.AddField(
            model_name='fight_history',
            name='obrance_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fight_history',
            name='utocnik_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
