# Generated by Django 5.1.5 on 2025-12-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0013_remove_fight_history_player_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight_history',
            name='obrance_name',
        ),
        migrations.RemoveField(
            model_name='fight_history',
            name='utocnik_name',
        ),
    ]
