# Generated by Django 5.1.5 on 2025-12-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightapp', '0014_remove_fight_history_obrance_name_and_more'),
        ('game', '0047_rename_quest_counter_player_quest_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight_history',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fight_histories', to='game.player'),
        ),
    ]
